# ==============================================================
# Backend Secret - REAL VALUES GO HERE
# NEVER COMMIT THIS FILE - add "k8s/backend-secret.yaml" to .gitignore
# ==============================================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: devsecops
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:clement@db:5432/taskdb"
  SECRET_KEY: "feb0f1a053a15a6ce1d42cf7418cecf06c6ea998a24b3a3df9582b0e370359b6"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"